# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38586fe81cceef788c1f0d83fe46bb31cd34273325eca83e0c7360ab6515c4b1b2c170ee63712ab0ddd902caa6f58f0e154388a4999a624834987934c74ae1e2

test:
  secret_key_base: 9910635816947ccf9eefd4e022e0b0cd93315165cee1a54b8544915afc9deb711cb343ffb68aa61cdf83f5f14728f207dc34019fe696f9ff4663e6f07f556c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
